### ISSUE TITLE
Expose a library API

### ISSUE THREAD

**Issue by xd009642** [wavey-ai/mel-spec#1]
So I was looking at using this as a library but none of the functionality seems publicly exposed? The readme looks quite impressive compared to the API functions docs.rs shows for the crate https://docs.rs/mel_spec/latest/mel_spec/index.html

**Comment by jbrough** [comment]
Ah, that's a good point I think this happened after I split things up into modules, I probably need to expose those via lib.rs, too.

I'll be pushing a big update later today that has a things nicely organised and an end-to-end example.

**Comment by xd009642** [comment]
Cool sounds good, I have a fork with the changes so I'll switch once the update is out

**Comment by jbrough** [comment]
This should all be sorted now and pushed up - its my first crate so if I've missed anything just let me know.
