### ISSUE TITLE
Error running the browser example

### ISSUE THREAD

**Issue by EzzatOmar** [wavey-ai/mel-spec#6]
Hi, I'm not really familiar with rust.

When running the browser example I got this error once transcription starts.
<img width="560" alt="image" src="https://github.com/wavey-ai/mel-spec/assets/19904006/f4f3b8db-73ec-461c-bbcb-fbca8bf63cf3">

Looking in mel_spec_pipeline.js I find this.

<img width="588" alt="image" src="https://github.com/wavey-ai/mel-spec/assets/19904006/8df7e4f2-1a2d-4bd0-8c87-93d1b388cc7d">

I on rustc version 1.78.0, cargo 1.78.0. MacBook M1 Pro.

When building I had some warnings but nothing dramatic.
Not sure where to start. 

Am I doing something wrong? Any help is welcomed. :)

**Comment by egorsmkv** [comment]
I am experiencing the same issue

**Comment by jbrough** [comment]
@egorsmkv I've pushed a fix for the voice activity detection example:

https://github.com/wavey-ai/mel-spec/commit/0361eef0d69bf631b09ae359f5d4ec5cbb873227

**Comment by egorsmkv** [comment]
@jbrough thank you! now it works!

<img width="1030" alt="image" src="https://github.com/user-attachments/assets/a1d5acc1-c3bd-425f-a63b-cbaa6b96ab02">

**Comment by jbrough** [comment]
@egorsmkv it's meant to work with whisper.cpp on M Macs (see tga_whisper example)  but I don't seem to have instructions about how to run that service on :9000 I'll look at adding that.

**Comment by egorsmkv** [comment]
As I see from the code it just sends POSTs request with TGA files to that address. Create a service that will respond with transcripts very easy looking on that demo.
